apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: rltrader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - image: 192.168.1.200:30000/redis:7.2
          name: redis
          ports:
            - containerPort: 6379
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: rltrader-role
                    operator: In
                    values: [inference]
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: rltrader
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
